---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-env-moodle
  namespace: jitsi
data:
  ENABLE_AUTH: "1"
  ENABLE_GUESTS: "1"
  AUTH_TYPE: internal
  DOCKER_HOST_ADDRESS: example.com
  PUBLIC_URL: https://example.com
  XMPP_BOSH_URL_BASE: http://127.0.0.1:5280
  XMPP_AUTH_DOMAIN: auth.example.com
  XMPP_MUC_DOMAIN: muc.example.com
  XMPP_GUEST_DOMAIN: guest.example.com
  XMPP_INTERNAL_MUC_DOMAIN: internal.muc.example.com
  XMPP_RECORDER_DOMAIN: recorder.example.com
  XMPP_SERVER: example.com
  XMPP_DOMAIN: example.com
  JICOFO_AUTH_USER: focus
  JICOFO_AUTH_PASSWORD: jicofoauthpassword
  JICOFO_COMPONENT_SECRET: jicofocomponentsecret
  JVB_AUTH_USER: jvb
  JVB_AUTH_PASSWORD: jvbauthpassword
  JVB_BREWERY_MUC: jvbbrewery
  JVB_TCP_PORT: "4443"
  JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
  JVB_TCP_HARVESTER_DISABLED: "true"
  JIBRI_XMPP_USER: jibri
  JIBRI_XMPP_PASSWORD: jibriauthpass
  JIBRI_BREWERY_MUC: JibriBrewery
  JIBRI_RECORDER_USER: recorder
  JIBRI_RECORDER_PASSWORD: jibrirecorderpass
  JIBRI_RECORDING_DIR: /config/recordings
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
  JIBRI_STRIP_DOMAIN_JID: muc
  JIBRI_LOGS_DIR: /config/logs
  JIBRI_PENDING_TIMEOUT: "200"
  ENABLE_RECORDING: "1"
  DISPLAY: :0
  TZ: Europe/Berlin
  DISABLE_CERTIFICATE_VERIFICATION: "false"
